title: IcecreamLab Games
description: Indie card & board game studio — online multiplayer card and board games for Android
url: "https://icecreamlabgames.com"
baseurl: "/icecreamlabgames"
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

